version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  #
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}  
    env_file:
      - .env 

  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  
    depends_on:
      - backend
